apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uwgmwtxvl-python
  janus-idp.io/tekton: uwgmwtxvl-python
  backstage.io/kubernetes-id: uwgmwtxvl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uwgmwtxvl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
